---
- hosts: webservers
  become: yes 
  
  tasks:
  - name: ensure appache is installed
    yum: name=httpd state=present
  
  - name: start apache
    service: name=httpd enabled=yes state=started


- hosts: dbservers
  become: yes

  tasks:
  - name: ensure mysql installed
    yum: name=mysql-server state=present 
  - name: start mysql
    service: name=mysqld state=started enabled=yes


- hosts: webservers:dbservers
  become: yes

  tasks:
  - name: stop iptables
    service: name=iptables, state=stopped enabled=no
