---
# tasks file for db

- name: Install MySQL
  yum:
    name: ['mysql-server','MySQL-python']
    state: latest
  notify: restart mysql


- name: Create database
  mysql_db:
    name: '{{ db_name }}'
    state: present

- name: Create user for the database
  mysql_user:
    name: '{{ db_user }}'
    password: '{{ db_pass }}'
    encrypted: yes
    priv: '{{ db_name }}.*:ALL'
    state: present

