---
# tasks file for web




- name: Install Zabbix-repo
  yum:
   name: https://repo.zabbix.com/zabbix/4.0/rhel/6/x86_64/zabbix-release-4.0-1.el6.noarch.rpm
   state: latest



- name: Install Zabbix-Agent
  yum:
   #name: zabbix-agent-4.0.10-1.el6
   name: https://repo.zabbix.com/zabbix/4.0/rhel/6/x86_64/zabbix-agent-4.0.10-1.el6.x86_64.rpm
   state: present
   allow_downgrade: yes

- name: Create a new host or update an existing host's info
  local_action:
    module: zabbix_host
    server_url: http://192.168.0.105/zabbix
    login_user: zabbix
    login_password: admin
    host_name: "{{ ansible_nodename }}"
    visible_name: ExampleName
    description: My ExampleHost Description
    host_groups:
      - Example group1
    link_templates:
      - Example template1
    status: enabled
    state: present
    inventory_mode: manual
    inventory_zabbix:
      tag: "{{ your_tag }}"
      alias: "{{ your_alias }}"
      notes: "Special Informations: {{ your_informations | default('None') }}"
      location: "{{ your_location }}"
      site_rack: "{{ your_site_rack }}"
      os: "{{ ansible_distribution }}"
      hardware: "{{ ansible_virtualization_type }}"
    interfaces:
      - type: 1
        main: 1
        useip: 1
        ip: "{{ ansible_default_ipv4.address }}"
        dns: ""
        port: 10050


- name: Install epel-release
  yum:
   name: epel-release
   state: latest






- name: Install Nginx
  yum:
   name: nginx
   state: latest

- name: Install PHP_FPM
  yum:
   name: ['php','php-fpm','php-common','php-cli','php-curl']
   state: latest


- name: Configure php.ini
  blockinfile:
    dest: /etc/php.ini
    #dest: /etc/php/{{ php_version }}/fpm/php.ini
    block: |
      date.time = Asia/Jakarta
      cgi-fix_pathinfo = 0
    backup: yes
  notify: restart php-fpm


- name: Create Nginx virtual host
  template:
    src: vhost.j2
    dest: /etc/nginx/conf.d/vhost-{{ domain_name }}
  notify: restart nginx


- name: Create web-root directory
  file:
    path: /var/www/{{ domain_name }}
    state: directory

- name: Upload index.html and info.php files
  template:
    src: index.php.j2
    dest: /var/www/{{ domain_name }}/index.php


